### ISSUE TITLE
Limit onnx threads to 1

### ISSUE THREAD

**Issue by mb706** [compstat-lmu/paper_2021_multi_fidelity_surrogates#20]
onnx seems to take as many threads as there are CPUs on the machine by default. However, when doing runs on machines with many CPUs, I would usually just want to have lots of R processes doing things in parallel, which results in #CPU^2 threads; this can actually cause problems if there is a limit of processes or file descriptors on the system.

What seems to work for me is
```r
rt = reticulate::import("onnxruntime")
opts = rt$SessionOptions()
opts$inter_op_num_threads = 1L
opts$intra_op_num_threads = 1L
session = rt$InferenceSession(model_path, sess_options = opts)
```
(although I am really not an expert and you should probably check this and see if there are other / better options to do this...)

**Comment by sumny** [comment]
closed by #23 see also #21
